//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomovilxSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutomovilxSucursal()
        {
            this.AutxSucxVentxClis = new HashSet<AutxSucxVentxCli>();
        }
    
        public int idAutomovilxSucursal { get; set; }
        public int idSucursal { get; set; }
        public bool estado { get; set; }
        public int idAutomovil { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutxSucxVentxCli> AutxSucxVentxClis { get; set; }
    }
}
