//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automovil()
        {
            this.CaracteristicasxAutomovils = new HashSet<CaracteristicasxAutomovil>();
            this.ExtraxAutomovils = new HashSet<ExtraxAutomovil>();
            this.FotoxAutomovils = new HashSet<FotoxAutomovil>();
        }
    
        public int idAutomovil { get; set; }
        public int idTipoAutomovil { get; set; }
        public int idTipoCombustible { get; set; }
        public string placa { get; set; }
        public decimal precioBase { get; set; }
        public bool consignacion { get; set; }
        public int anno { get; set; }
    
        public virtual TipoAutomovil TipoAutomovil { get; set; }
        public virtual TipoCombustible TipoCombustible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicasxAutomovil> CaracteristicasxAutomovils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraxAutomovil> ExtraxAutomovils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoxAutomovil> FotoxAutomovils { get; set; }
    }
}
