//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutxSucxVentxCli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutxSucxVentxCli()
        {
            this.Detalles = new HashSet<Detalle>();
        }
    
        public int idAutxSucxVentxCli { get; set; }
        public int idAutomovilxSucursal { get; set; }
        public int idVentaxCliente { get; set; }
    
        public virtual AutomovilxSucursal AutomovilxSucursal { get; set; }
        public virtual VentasxCliente VentasxCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalles { get; set; }
    }
}
