//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristicasxAutomovil
    {
        public int idCaracteristicasxAutomovil { get; set; }
        public int idCaracteristica { get; set; }
        public int idAutomovil { get; set; }
    
        public virtual Automovil Automovil { get; set; }
        public virtual Caracteristica Caracteristica { get; set; }
    }
}
