//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoFabrica
    {
        public int idEmpleadoFabrica { get; set; }
        public int idFabrica { get; set; }
        public string nombre { get; set; }
        public int cedula { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
    
        public virtual Fabrica Fabrica { get; set; }
    }
}
