//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoSucursal3
    {
        public int idPedido { get; set; }
        public int idFabrica { get; set; }
        public int idAutomovilxSucursal { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fechaPedido { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public bool despacho { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Fabrica Fabrica { get; set; }
    }
}
