//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalUbicacion
    {
        public int idSucursalUbicacion { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public System.Data.Entity.Spatial.DbGeometry ubicacion { get; set; }
        public string pais { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
