//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutomoviles
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaxCliente
    {
        public int idVentaxCliente { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idVenta { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
